/*
 * File: app/view/About.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.About', {
    extend: 'Ext.Panel',

    config: {
        html: '<br/><center><h2>Whiteboard Capture</h2><br/><h4>Team Bright House</h4><br/>Zac Turnbow<br/>Tommy Adamski<br/>Jeff Downing<br/>Sam Weirich<br/>Gabriel Reiser<br/><br/><img height=60 width=160 src="http://www.sencha.com/img/sencha-large.png"><br/><br/><img src="http://julien.danjou.info/media/images/github.svg" height=60 width=160><a href="https://github.com/zturnbow/Sencha13Hackathon">https://github.com/zturnbow/Sencha13Hackathon</a></center>',
        id: 'about',
        itemId: 'about',
        styleHtmlContent: true
    }

});