/*
 * File: app/view/CaptureInterfaceView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.CaptureInterfaceView', {
    extend: 'Ext.Container',

    config: {
        items: [
            {
                xtype: 'button',
                handler: function(button, event) {
                    Ext.device.Camera.capture({
                        success: function(image) {
                            var imageView = Ext.getCmp('capturedImage');
                            imageView.setSrc(image);
                        },                          
                        destination: 'camera'
                    });
                },
                docked: 'bottom',
                ui: 'action',
                text: 'Capture'
            }
        ]
    }

});