/*
 * File: app/view/MainMenuView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.MainMenuView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainMenuView',

    config: {
        hideAnimation: 'fadeOut',
        id: 'mainMenuView',
        itemId: 'mainMenuView',
        showAnimation: 'fadeIn',
        layout: {
            animation: {
                type: 'slide',
                duration: 200
            },
            type: 'card'
        },
        navigationBar: {
            docked: 'top',
            androidAnimation: false,
            items: [
                {
                    xtype: 'button',
                    align: 'right',
                    itemId: 'logout',
                    ui: 'small',
                    text: 'Logout'
                },
                {
                    xtype: 'button',
                    ui: 'back',
                    text: 'Back'
                },
                {
                    xtype: 'label',
                    centered: false,
                    html: 'Whiteboard Capture',
                    ui: 'dark'
                }
            ]
        },
        listeners: [
            {
                fn: 'onMainMenuViewActivate',
                event: 'activate'
            }
        ]
    },

    onMainMenuViewActivate: function(newActiveItem, container, oldActiveItem, eOpts) {

    }

});