/*
 * File: app/view/WhiteboardAddPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.WhiteboardAddPanel', {
    extend: 'Ext.Panel',

    config: {
        id: 'WhiteboardAddPanel',
        items: [
            {
                xtype: 'image',
                centered: false,
                height: 201,
                id: 'capturedPhoto',
                itemId: 'capturedPhoto',
                margin: '20% 0 0 0',
                src: 'resources/images/blank.png'
            },
            {
                xtype: 'button',
                centered: false,
                id: 'whiteboardAddPhoto',
                itemId: 'whiteboardAddPhoto',
                left: '',
                margin: '0 20% 0 20%',
                ui: 'action',
                icon: 'true',
                iconCls: 'add',
                text: 'Take Photo'
            },
            {
                xtype: 'button',
                hidden: true,
                id: 'whiteboardSavePhoto',
                itemId: 'whiteboardSavePhoto',
                margin: '10 20% 0 20%',
                ui: 'confirm',
                iconCls: 'action',
                text: 'Save Photo'
            }
        ]
    }

});