/*
 * File: app/view/WhiteboardPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.WhiteboardPanel', {
    extend: 'Ext.Panel',

    config: {
        id: 'WhiteboardPanel',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'list',
                id: 'WhiteboardList',
                itemTpl: [
                    '<div class="imageWrapper">',
                    '    <div class="projectTitle">{project}</div>',
                    '    <div class="image"><img src="{image}"/></div>',
                    '    <div class="imageDesc">{description}</div>',
                    '</div>'
                ],
                store: 'WhiteboardStore',
                plugins: [
                    {
                        type: 'pullrefresh'
                    }
                ]
            }
        ]
    }

});