/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({

    requires: [
        'Ext.device.Camera'
    ],
    models: [
        'User',
        'Project',
        'Whiteboard'
    ],
    stores: [
        'UserStore',
        'ProjectStore',
        'WhiteboardStore'
    ],
    views: [
        'MainMenuView',
        'RegisterView',
        'ProjectPanel',
        'WhiteboardPanel',
        'WhiteboardAddPanel'
    ],
    controllers: [
        'LoginController',
        'RegisterController',
        'LogoutController',
        'ProjectController',
        'WhiteboardController',
        'ProjectAddController'
    ],
    name: 'app',
    startupImage: {
        '320x460': 'resources/images/splash-screen-hi-res.png',
        '640x920': 'resources/images/splash-screen-hi-res.png',
        '640x1096': 'resources/images/splash-screen-hi-res.png',
        '768x1004': 'resources/images/splash-screen-hi-res.png',
        '748x1024': 'resources/images/splash-screen-hi-res.png',
        '1536x2008': 'resources/images/splash-screen-hi-res.png',
        '1496x2048': 'resources/images/splash-screen-hi-res.png'
    },

    launch: function() {

        Ext.create('app.view.MainMenuView', {fullscreen: true});
    }

});
