/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.controller.LoginController', {
    extend: 'Ext.app.Controller',

    config: {
        models: [
            'user'
        ],
        views: [
            'LoginView'
        ],

        control: {
            "#submit": {
                tap: 'onButtonTap'
            }
        }
    },

    onButtonTap: function(button, e, eOpts) {
		var Users = Ext.getStore('app.store.userStore');
        var uname = Ext.ComponentMgr.get("username").getValue();
        var pass = Ext.ComponentMgr.get("password").getValue();

        
        var user = Users.findBy(function(record, id){
            if(record.username == uname && record.password == pass){
                alert("found!");
                return id;
            } else {
                alert("notfound!");
                return -1;
            }
        });
		console.log(user);
    }

});