/*
 * File: app/controller/RegisterController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.controller.RegisterController', {
    extend: 'Ext.app.Controller',

    config: {
        models: [
            'user'
        ],
        views: [
            'RegisterView'
        ],

        control: {
            "registerView #register": {
                tap: 'onRegister'
            },
            "registerView #cancel": {
                tap: 'onCancel'
            }
        }
    },

    onRegister: function(button, e, eOpts) {

    },

    onCancel: function(button, e, eOpts) {
        var login = Ext.create("app.view.LoginView",{fullscreen:true});
        Ext.Viewport.remove(Ext.ComponentMgr.get("registerView"));
        Ext.Viewport.add(login);
        Ext.Viewport.setActiveItem(login);
    }

});