/*
 * File: app/controller/WhiteboardController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.controller.WhiteboardController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#whiteboardAddPhoto": {
                tap: 'onAddPhoto'
            },
            "#WhiteboardPanel": {
                activate: 'onWhiteboardPanelActivate'
            },
            "#whiteboardSavePhoto": {
                tap: 'onSavePhoto'
            }
        }
    },

    onAddPhoto: function(button, e, eOpts) {
        /*Ext.device.Camera.capture({
        quality:100,
        destination: 'data',
        source:'camera',
        success: function(data) {
        this.fireEvent('change', this, data);
        },
        failure: function() {
        Ext.Msg.alert('Error', 'There was an error when acquiring the picture.');
        },
        scope: this
        });*/
        var _this = this;
        $('body').once('photo_capture', function(event, data){
            Ext.ComponentMgr.get("capturedPhoto").setSrc(data);
            Ext.ComponentMgr.get("whiteboardAddPhoto").hide();
            Ext.ComponentMgr.get("whiteboardSavePhoto").show();
        });
        $('#picture').click();
    },

    onWhiteboardPanelActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        var button = Ext.ComponentManager.get("AddNewButton");
        if(button){
            button.setVisibility(true);
            button.setText("Whiteboard");
        }

        Ext.Viewport.setMasked({ xtype: 'loadmask', message: 'Loading Whiteboards...' });

    },

    onSavePhoto: function(button, e, eOpts) {
        var photodata = Ext.ComponentMgr.get("capturedPhoto").getSrc();
        Ext.Viewport.setMasked({ xtype: 'loadmask', message: 'Saving Photo...' });
        Ext.Ajax.request({
            url: "https://"+settings.server_host+"/api/whiteboards/"+settings.record.data.name,
            method: "POST",
            params: { mimetype: "image/jpeg", image:photodata },
            success: function(response) {
                var msg = Ext.JSON.decode(response.responseText);
                if(msg.success){
                    Ext.Viewport.setMasked(false);
                    Ext.ComponentMgr.get("MainMenuView").pop();
                } else {
                    Ext.Viewport.setMasked(false);
                    Ext.Msg.alert('Save Failure', 'Unable to save image.');
                }
            }
        });
    }

});