/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Login', {
    extend: 'Ext.navigation.View',

    config: {
        ui: '',
        scrollable: true,
        layout: {
            animation: 'pop',
            type: 'card'
        },
        items: [
            {
                xtype: 'panel',
                title: 'White Board Login',
                items: [
                    {
                        xtype: 'emailfield',
                        label: 'E-mail',
                        name: 'email',
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'passwordfield',
                        label: 'Password',
                        name: 'password'
                    },
                    {
                        xtype: 'button',
                        centered: true,
                        ui: 'action-round',
                        width: 100,
                        iconAlign: 'center',
                        text: 'Submit'
                    }
                ]
            }
        ]
    }

});